# version: "3.8"
# services:
#   nginx:  
#     image: nginx:1.27.0
#     ports:
#       - 80:80
#     volumes: 
#       - ../build:/usr/share/nginx/html  

version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    volumes:
      - ..:/usr/src/app
    environment:
      - NODE_ENV=development